import { MeleeWeaponStatObject } from "@srd/common/interfaces/chapterInterfaces/EquipmentInterfaces"

export const polearmStats: MeleeWeaponStatObject[] = [
    {
        name: 'Ahlspiess',
        size: 'L',
        damage: '2d8!',
        recovery: 9,
        damageType: 'P',
        parry: 0,
        measure: 6,
        oneHanding: true,
        brace: true,
    },
    {
        name: 'Bill',
        size: 'L',
        damage: '2d10!',
        recovery: 13,
        damageType: 'P',
        parry: 0,
        measure: 7.25,
        brace: true,
    },
    {
        name: 'Glaive',
        size: 'L',
        damage: '4d4!',
        recovery: 14,
        damageType: 'S',
        parry: 0,
        measure: 8,
        bonus: true
    },
    {
        name: 'Halberd',
        size: 'L',
        damage: '5d4!',
        recovery: 17,
        damageType: 'S',
        parry: 0,
        measure: 5,
        bonus: true
    },
    {
        name: 'Halberd',
        size: 'L',
        damage: '2d8!',
        recovery: 10,
        damageType: 'P',
        parry: 0,
        measure: 5,
        bonus: true,
        brace: true
    },
    {
        name: 'Javelin',
        size: 'M',
        damage: '2d6!',
        recovery: 13,
        damageType: 'P',
        parry: 0,
        measure: 4.25,
        bonus: true,
        oneHanding: true
    },
    {
        name: 'Lance',
        size: 'L',
        damage: '1d8!',
        recovery: 24,
        damageType: 'P',
        parry: 0,
        measure: 10,
        bonus: true,
        brace: true
    },
    {
        name: 'Lucerne',
        size: 'L',
        damage: 'd20!',
        recovery: 13,
        damageType: 'C',
        parry: 0,
        measure: 7,
    },
    {
        name: 'Military Fork',
        size: 'L',
        damage: '3d4!',
        recovery: 12,
        damageType: 'P',
        parry: 0,
        measure: 6.75,
        bonus: true
    },
    {
        name: 'Pike',
        size: 'H',
        damage: '4d8!',
        recovery: 12,
        damageType: 'P',
        parry: 0,
        measure: 23,
        brace: true
    },
    {
        name: 'Planson',
        size: 'S',
        damage: '2d6!',
        recovery: 10,
        damageType: 'P',
        parry: 2,
        measure: 4,
        oneHanding: true
    },
    {
        name: 'Ranseur',
        size: 'L',
        damage: '2d8!',
        recovery: 10,
        damageType: 'P',
        parry: 4,
        measure: 8,
        oneHanding: true,
        brace: true,
    },
    {
        name: 'Short Spear',
        size: 'M',
        damage: '2d8!',
        recovery: 11,
        damageType: 'P',
        parry: 0,
        measure: 5,
        oneHanding: true,
    },
    {
        name: 'Voulge',
        size: 'L',
        damage: '8d3!',
        recovery: 20,
        damageType: 'S',
        parry: 0,
        measure: 8,
        brace: true
    },
    {
        name: 'War-scythe',
        size: 'L',
        damage: '6d3!',
        recovery: 19,
        damageType: 'P',
        parry: 0,
        measure: 6.25,
    }
]

export const polearmStatsFree: MeleeWeaponStatObject[] = [
    {
        name: 'Ranseur',
        size: 'L',
        damage: '2d8!',
        recovery: 10,
        damageType: 'P',
        parry: 4,
        measure: 8,
        oneHanding: true,
        brace: true,
    },
    {
        name: 'Short Spear',
        size: 'M',
        damage: '2d8!',
        recovery: 11,
        damageType: 'P',
        parry: 0,
        measure: 5,
        oneHanding: true,
    },
]