export default {
    free: "select book, section, chapter, substring(freesearch, startPosition, endPosition - startPosition) as excerpt from ( select book, section, chapter, position (UPPER($1) in upper(freesearch)) - 25 as startPosition, length(freesearch) - position (reverse(UPPER($1)) in reverse(upper(freesearch)))  + 25 as endPosition, freesearch from srdchapters s where UPPER(freesearch) like UPPER(( '%' || $1 || '%' )) and book = 'rules' ) sr",
    player: "select book, section, chapter, substring(freesearch, startPosition, endPosition - startPosition) as excerpt from ( select book, section, chapter, position (UPPER($1) in upper(freesearch)) - 25 as startPosition, length(freesearch) - position (reverse(UPPER($1)) in reverse(upper(freesearch)))  + 25 as endPosition, freesearch from srdchapters s where UPPER(freesearch) like UPPER(( '%' || $1 || '%' )) and book != 'gms' ) sr",
    deluxe: "select book, section, chapter, substring(deluxesearch, startPosition, endPosition - startPosition) as excerpt from ( select book, section, chapter, position (UPPER($1) in upper(deluxesearch)) - 25 as startPosition, length(deluxesearch) - position (reverse(UPPER($1)) in reverse(upper(deluxesearch)))  + 25 as endPosition, deluxesearch from srdchapters s where UPPER(deluxesearch) like UPPER(( '%' || $1 || '%' )) and book != 'gms' ) sr",
    gm: "select book, section, chapter, substring(deluxesearch, startPosition, endPosition - startPosition) as excerpt from ( select book, section, chapter, position (UPPER($1) in upper(deluxesearch)) - 25 as startPosition, length(deluxesearch) - position (reverse(UPPER($1)) in reverse(upper(deluxesearch)))  + 25 as endPosition, deluxesearch from srdchapters s where UPPER(deluxesearch) like UPPER(( '%' || $1 || '%' )) ) sr",
    updateFree: "update srdchapters set freesearch = $1 where book = $2 and chapter = $3",
    updateFreeWithSection: "update srdchapters set freesearch = $1 where book = $2 and section = $3 and chapter = $4",
    updateDeluxe: "update srdchapters set deluxesearch = $1 where book = $2 and chapter = $3",
    updateDeluxeWithSection: "update srdchapters set deluxesearch = $1 where book = $2 and section = $3 and chapter = $4"
}